ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "birth_latitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "birth_longitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "birth_timezone" TEXT,
ADD COLUMN IF NOT EXISTS "birth_time_known" BOOLEAN NOT NULL DEFAULT true;
